[package]
name = "dbc_parser"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"
authors = ["Kevin Herro kvherro@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.9"
